import { formatUsdt } from "@/lib/utils";

const tiers = [
  { level: "Level 1 (direct)", rate: "15%", example: 1125 },
  { level: "Level 2", rate: "10%", example: 750 },
  { level: "Level 3", rate: "5%", example: 375 },
];

export default function ReferralPage() {
  const referralLink = "https://app.agentra.network/r/AGT-demo8K2";

  return (
    <div className="space-y-6 pb-4">
      <header className="max-w-2xl">
        <h1 className="text-2xl font-bold text-slate-900 sm:text-3xl">Referral program</h1>
        <p className="mt-2 text-sm text-slate-600 sm:text-base">
          Commissions are paid on <strong>actual net profits</strong> generated by referred
          accounts—not on deposits or losses. Payouts accrue to your USDT TRC-20 wallet on the
          same 24-hour UTC cycle as the settlements dashboard.
        </p>
      </header>

      <div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm">
        <p className="text-xs font-semibold uppercase text-slate-500">Your link</p>
        <p className="mt-2 break-all font-mono text-sm text-teal-800">{referralLink}</p>
        <p className="mt-2 text-xs text-slate-500">
          Referral codes are verifiable in URL params and in account settings after signup.
        </p>
      </div>

      <div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm">
        <table className="w-full text-left text-sm">
          <thead className="bg-stone-50 text-xs uppercase text-slate-500">
            <tr>
              <th className="px-4 py-3">Tier</th>
              <th className="px-4 py-3">Rate on referral net profit</th>
              <th className="px-4 py-3 text-right">Example commission (USDT)</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-stone-100">
            {tiers.map((t) => (
              <tr key={t.level}>
                <td className="px-4 py-3 font-medium">{t.level}</td>
                <td className="px-4 py-3">{t.rate}</td>
                <td className="px-4 py-3 text-right tabular-nums">
                  {formatUsdt(t.example)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <p className="border-t border-stone-100 px-4 py-3 text-xs text-slate-500">
          Example assumes referred users collectively earn $7,500 net profit in a cycle (illustrative
          only—not a guarantee).
        </p>
      </div>

      <section className="rounded-2xl border border-stone-200 bg-stone-50 px-4 py-4 text-sm text-slate-600">
        <strong className="text-slate-800">Compliance note (E):</strong> Multi-level referral
        programs may be treated as MLM or securities marketing in some jurisdictions. Obtain legal
        review before launch; disclose that profits are not guaranteed and past results do not
        predict future performance.
      </section>
    </div>
  );
}
